
server:
  port: 7001

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/udemy
    username: {  }
    password: {  }
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    show_sql: true

